name: persona
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
      - frontend

  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install;npm run dev"
    expose:
      - 3000
    volumes:
      - ./backend:/backend
    environment:
      - PG_DATABASE=${DB_DATABASE}
      - PG_USER=${DB_USERNAME}
      - PG_PASSWORD=${DB_PASSWORD}
      - PG_HOST=database

  frontend:
    container_name: frontend
    image: nginx:alpine
    expose:
      - 80
    volumes:
      - ./frontend:/usr/share/nginx/html

  database:
    image: database
    container_name: database_persona
    build: ./database
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}