name: persona
services:
  backend:
    image: backend:production
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install;npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend

  frontend:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./frontend/form:/usr/share/nginx/html/form
      - ./frontend/peopleList:/usr/share/nginx/html/peopleList
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html
