name: caso2
services:
  backend:
    image: backend:production
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install;npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
