name: persona
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./certs:/etc/nginx/certs
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_ID=${GOOGLE_CLIENT}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
    depends_on:
      - backend
      - frontend

  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install && npm run dev"
    expose:
      - 3000
    volumes:
      - ./backend:/backend
    environment:
      - PGDATABASE=${DB_DATABASE}
      - PGUSER=${DB_USERNAME}
      - PGPASSWORD=${DB_PASSWORD}
      - PGHOST=database
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_SECRET}
      - FRONTEND_URL=${FRONT_URL}

  frontend:
    container_name: frontend
    image: nginx:alpine
    expose:
      - 80
    volumes:
      - ./frontend:/usr/share/nginx/html

  database:
    image: database
    container_name: database_persona
    build: ./database
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}